version: '2'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
 minio1:
  image: minio/minio:RELEASE.2018-10-18T00-28-58Z
  volumes:
   - ./data1:/data
  ports:
   - "9001:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data http://minio5/data http://minio6/data
 minio2:
  image: minio/minio:RELEASE.2018-10-18T00-28-58Z
  volumes:
   - ./data2:/data
  ports:
   - "9002:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data http://minio5/data http://minio6/data
 minio3:
  image: minio/minio:RELEASE.2018-10-18T00-28-58Z
  volumes:
   - ./data3:/data
  ports:
   - "9003:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data http://minio5/data http://minio6/data
 minio4:
  image: minio/minio:RELEASE.2018-10-18T00-28-58Z
  volumes:
   - ./data4:/data
  ports:
   - "9004:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data http://minio5/data http://minio6/data
 minio5:
  image: minio/minio:RELEASE.2018-10-18T00-28-58Z
  volumes:
   - ./data5:/data
  ports:
   - "9005:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data http://minio5/data http://minio6/data

 minio6:
  image: minio/minio:RELEASE.2018-10-18T00-28-58Z
  volumes:
   - ./data6:/data
  ports:
   - "9006:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data http://minio5/data http://minio6/data
 mcsetup1:
  image: minio/mc:latest
  command: "config host add minio1 http://minio1:9000 minio minio123"
  volumes:
   - ./mc:/root/
 mcsetup2:
  image: minio/mc:latest
  command: "config host add minio2 http://minio2:9000 minio minio123"
  volumes:
   - ./mc:/root/
 mcsetup3:
  image: minio/mc:latest
  command: "config host add minio3 http://minio3:9000 minio minio123"
  volumes:
   - ./mc:/root/
 mcsetup4:
  image: minio/mc:latest
  command: "config host add minio4 http://minio4:9000 minio minio123"
  volumes:
   - ./mc:/root/
 mcsetup5:
  image: minio/mc:latest
  command: "config host add minio5 http://minio5:9000 minio minio123"
  volumes:
   - ./mc:/root/
 mcsetup6:
  image: minio/mc:latest
  command: "config host add minio6 http://minio6:9000 minio minio123"
  volumes:
   - ./mc:/root/
 mc:
  image: minio/mc:latest
  volumes:
   - ./mc:/root/

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
#volumes:
        #        data1:
                #        data2:
                #        data3:
                #        data4:
                #        data5:
                #        data6:
